### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Gaurav0** [jessica-jordan/whats-new-in-emberland#5]
Please tell us how to use this application

**Comment by amyrlam** [comment]
Heya - I have this mentioned on the Ember Times, because it's something we use (run locally following https://github.com/jessica-jordan/whats-new-in-emberland#installation) to check all repos across `emberjs` and `ember-learn` for things that have happened in the last week. 

But I'm having an issue with copying the contributors as I described in https://github.com/jessica-jordan/whats-new-in-emberland/issues/4
